### ISSUE TITLE
Odroid HC1/XU4

### ISSUE THREAD

**Issue by unixfox** [sgielen/picl-k3os-image-generator#13]
Hello,

Thank you for creating this generator.

I would like to know if you could add support for the Odroid HC1/XU4 (it's the same device).

I know archlinux arm has support for it so maybe this could help you about that: https://archlinuxarm.org/platforms/armv7/samsung/odroid-hc1

Thank you

**Comment by sgielen** [comment]
I'm looking at that device but it looks like its CPU is 32-bit only (correct me if I'm wrong).

The ODROID-C2 seems to have a 64-bit capable CPU so it would be able to run the aarch64 kernel.

**Comment by unixfox** [comment]
Sure but K3OS support ARM 32bits if I'm not mistaken?

**Comment by sgielen** [comment]
> > I'm looking at that device but it looks like its CPU is 32-bit only (correct me if I'm wrong).
> 
> That's correct but K3OS support ARM 32bits if I'm not mistaken?

k3os itself yes, but the rest of the script uses 64-bit dependencies, and I consider it a waste of time to invest in 32-bit support. Consider also that most Docker images / Kubernetes projects ported to arm are only ported to arm64, so with 32-bit ARM you might find yourself still not being able to run the software you want. :)

**Comment by edrex** [comment]
armv6/armhf container image builds are actually available for quite a lot of components. It's not an issue of porting so much as producing a build, so long as the contained component has been ported.

I have two odroid HC2s in which I am currently investing some time to set up as k3os nodes for storage-intensive edge applications, and I am considering forking your script as a starting point (seems well organized, good bashing!)

My main concern with all approaches starting with an existing OS image is how to automate updates to the underlying kernel. I would like to be able to use https://github.com/rancher/system-upgrade-controller to automate kernel updates in addition to /k3os/system (https://github.com/rancher/k3os#automatic-upgrades). Any ideas there welcome :cake:

**Comment by edrex** [comment]
Following up on my last comment, it seems like an [overlay installation](https://github.com/rancher/k3os#arm-overlay-installation) leaves the existing userland in place, so it should be possible to use apt or whatever to pull in kernel updates, although care would need to be taken to preserve k3os's `/sbin/init`. Perhaps this could be used with system-upgrade-controller to keep all host OS components up to date, without the need for flashing new root images. Does this seem right?
