### ISSUE TITLE
Question: RPi4 Netboot

### ISSUE THREAD

**Issue by sipodd** [sgielen/picl-k3os-image-generator#21]
Not sure if this is more related to the Image Generator or the OS itself, but I would really love to use this without an SDcard.

Can I use this image with netboot option, like Rasbian?

**Comment by sgielen** [comment]
I have no experience with Raspberry Pi netboot or how to get it started. But you're very welcome to try and report what you find, and I'll try to help you out if you run into something image-related :)

**Comment by jkoby** [comment]
Looks like it involves making sure TFTP and NFS are both available on the local network: https://www.raspberrypi.org/documentation/hardware/raspberrypi/bootmodes/net_tutorial.md

**Comment by sgielen** [comment]
Closing all issues, because the project is archived. Thank you for being a contributor and/or user!
