### ISSUE TITLE
How to correctly fix init.resizefs when booting rpi from ssd

### ISSUE THREAD

**Issue by Ognian** [sgielen/picl-k3os-image-generator#27]
When generating the image for raspberry pi and burning it to a ssd, so that the rpi boots from the usb disk instead of the sd card
everything it needs to be changed is this [line](https://github.com/sgielen/picl-k3os-image-generator/blob/1f07d533331a73f4f8a864b5e7947674e8f95936/init.resizefs#L41) ('p1' to '1')  to make the install successful.
I'm not sure how we shall fix this. One possibility is to add a third '$IMAGE_TYPE' -> raspberrypiusb but this would lead to many changes in the if's which would make the code less readable. Another would be to add a '$IMAGE_SUBTYPE'...
The most elegant way would be to somehow programmatically find out the name of the first partition of the '$ROOTDISK'...
Any ideas ?

**Comment by Ognian** [comment]
Added https://github.com/Ognian/picl-k3os-image-generator/commit/e562ca5e77fc705d6f89a158864e2c8260991c26 but it is not tested yet... (don't have empty sd and/or usb ssd's now)

**Comment by sgielen** [comment]
I think programmatically finding out the name of the first partition should be feasible. I guess the name of the disk is quite unpredictable and can also change in the future, so I would prefer not to hardcode any expectations of it. In that sense, I'd gladly get rid of this hardcoding of the expected name of the first partition.

Tools like `lsblk` are able to find out a partition tree from a block device, perhaps using /sys or /proc, I think it would be a good idea to find out how they do it, and use similar behaviour here.

**Comment by Ognian** [comment]
Changed to https://github.com/Ognian/picl-k3os-image-generator/commit/23ede0c723b842e536a5c881ccf6e4f7149aa80b should work but is still not tested...

**Comment by cwoolum** [comment]
I was able to test this. I used the changes from both commits but get an error.

```
lsblk: error while loading shared libraries: libmount.so.1: cannot open shared object file: No such file or directory
mount: can't read '/etc/fstab': No such file or directory
```

**Comment by cwoolum** [comment]
I tried flashing a regular SD Card again afterward and failed due to the regex not matching. Since we're using sh instead of bash, the syntax needs to be a bit different.

```
if echo "$ROOTDISK" | grep -Eq $MMCROOT_REGEX; then
```

**Comment by sgielen** [comment]
Just pushed as b3ed5f16f506c5dea8d241c23088535e768919d2, thank you @Ognian and @cwoolum :-)
