### ISSUE TITLE
is image well formed ?

### ISSUE THREAD

**Issue by Tchoupinax** [sgielen/picl-k3os-image-generator#3]
Hello, 

i installed the image created by your script on a raspberry pi 4. I connected with ssh to my cluster and it is ok but i have several errors: 
- Cluster is not working (`The connection to the server localhost:8080 was refused`).
- The file to recover the configuration (`/etc/rancher/k3s/k3s.yaml`) does not exist (while it exists in normal k3os image).

Is something missing in your script ? :)

Thank you for your work :)

**Comment by sgielen** [comment]
Can you check whether `k3s agent` is running normally on the system? If not, could you take a look at the logs in `/var/log` to see if you can find out why it's not running?

**Comment by sgielen** [comment]
No response for over a month, closing.
