### ISSUE TITLE
[Question] Is there a way to add binaries ?

### ISSUE THREAD

**Issue by Neonox31** [sgielen/picl-k3os-image-generator#31]
Hello @sgielen 

I tried to add wireless-tools using 
```bash
dl_dep wireless-tools_30~pre9-12ubuntu1_arm64.deb https://launchpadlibrarian.net/317368711/wireless-tools_30~pre9-12ubuntu1_arm64.deb
...
unpack_deb "wireless-tools_30~pre9-12ubuntu1_arm64.deb" "root"
```
Binaries are present in the `/sbin` sdcard folder but never appears from `/sbin` folder after booting.
I presume this is due to k3OS rootfs which erases all file system during first boot ? If yes, is there a solution to add these binaries during image creation ?

Thanks a lot

**Comment by darac** [comment]
Hello,

It looks like k3os's rootfs is available at `root/k3os/data`, so you might want to look at unpacking there. That *might* only be available after first boot, but it's good enough for me at the moment :)

**Comment by sgielen** [comment]
Closing all issues, because the project is archived. Thank you for being a contributor and/or user!
