### ISSUE TITLE
Cannot boot from USB on Raspberry Pi 4

### ISSUE THREAD

**Issue by cwoolum** [sgielen/picl-k3os-image-generator#32]
I'm trying to boot from a usb drive on my Raspberry Pi 4. I have updated the bootloader to support USB booting and Raspian boots fine. When I try to boot this image though, I get the following errors:

```
recovery4.elf: not found (6)
recovery4.elf: not found (6)

Read start4.elf bytes 2784800
Read fixup4.elf bytes      6200
0x00c03111 0x00000000 0x00000007
start4.elf is not compatible. 
USB-MSD boot requires newer software.
```

I tried applying the changes from #27 but I don't think they are related to this.

I'm building using `RASPBERRY_PI_FIRMWARE=latest`. I also tried deleting everything in `deps` to make sure I was getting the latest of everything.

I also updated `build-image.sh` to get the latest rootfs image.

`dl_dep k3os-rootfs-arm64.tar.gz https://github.com/rancher/k3os/releases/download/v0.11.1/k3os-rootfs-arm64.tar.gz`

**Comment by bdsoha** [comment]
Same issue here.

**Comment by cwoolum** [comment]
@sgielen, do you have any experience with modifying images to support USB boot? I found some instructions to make a Ubuntu image for Raspberry Pi that supports that functionality but it uses a different bootloader so it's not relevant to this.

**Comment by cwoolum** [comment]
I was able to resolve this. The default version of the raspberry pi firmware that this script used was not compatible with USB boot. The solution to fix this is to delete `deps/raspberrypi-firmware.tar`, set `export RASPBERRY_PI_FIRMWARE=latest`, and then rerun the `build-image.sh` script.

#27 is still an outstanding item though.

**Comment by bdsoha** [comment]
@cwoolum I am running the latest firmware and still having this issue.
