### ISSUE TITLE
KVM and Wireguard modules

### ISSUE THREAD

**Issue by kwiesmueller** [sgielen/picl-k3os-image-generator#37]
Hey there,
I just put an image generated with this tool onto my Pi4.
There seems to be some discrepancy with original K3os as it supports both kvm and wireguard modules but I get errors enabling those on an actual Pi (modules not found).

Do you have a suggestion on where/what I'd have to add to get those modules?

**Comment by kwiesmueller** [comment]
Okay, at least wireguard I got by using the latest firmware. Not sure about KVM yet.

**Comment by mazzy89** [comment]
this process does not use k3os kernel which is an ubuntu based kernel with those modules enabled. it uses the official RPI ones which have a lot of modules disabled because of the resources constraint.

**Comment by sgielen** [comment]
Closing all issues, because the project is archived. Thank you for being a contributor and/or user!
