### ISSUE TITLE
Poe Hat fan support

### ISSUE THREAD

**Issue by mazzy89** [sgielen/picl-k3os-image-generator#44]
I'm currently try to bake an image for RPI 4 with the support for the fan mounted on top of the PoE hat. Currently booting k3os gives as result that the fan does not spin hence the pi is super hot. Did anyone try that?

**Comment by mazzy89** [comment]
I will try to add to the config boot the parameter https://github.com/raspberrypi/firmware/blob/46f356dcecc5204ca9a8cef7e6894e083b231bc7/boot/overlays/README#L2609 and bake again an image to see if the fan goes up

**Comment by mazzy89** [comment]
I confirm that adding these parameters to the `config.txt` it works:

```
dtoverlay=rpi-poe-plus
dtparam=poe_fan_temp0=10000,poe_fan_temp0_hyst=1000
dtparam=poe_fan_temp1=55000,poe_fan_temp1_hyst=5000
dtparam=poe_fan_temp2=60000,poe_fan_temp2_hyst=5000
dtparam=poe_fan_temp3=65000,poe_fan_temp3_hyst=5000
```

**Comment by SSvilen** [comment]
I've just tried it on my 4B using the latest firmware and it works.

**Comment by mazzy89** [comment]
I think then we can close this. solved.
