### ISSUE TITLE
CNI like Cilium won't on k3os run using the official firmware pulled

### ISSUE THREAD

**Issue by mazzy89** [sgielen/picl-k3os-image-generator#45]
The script pulls the RPI firmware from the official repo. At the time of this writing, I've pulled the RPI firmware `1.20210831`

Gettig the kernel config out of this firmware, I've found out that important kernel config in order for Cilium to run are not present.

In particular, those two are missing:

```
CONFIG_NET_CLS_BPF
CONFIG_BPF_JIT
```

and these two 

```
CONFIG_NET_SCH_INGRESS
CONFIG_CRYPTO_USER_API_HASH
```
are set to `m`. 

According to Cilium docs those should have been enabled https://docs.cilium.io/en/stable/operations/system_requirements/#linux-kernel

Which is the best approach here? Bake a custom kernel or go upstream and ask if those parameters can be enabled?

It would make sense the latter since k3os officially supports Cilium.

**Comment by sgielen** [comment]
Closing all issues, because the project is archived. Thank you for being a contributor and/or user!
