### ISSUE TITLE
RPi-Distro renamed master to buster

### ISSUE THREAD

**Issue by Rojikku** [sgielen/picl-k3os-image-generator#46]
In multiple locations the script calls for rpi-firmware-nonfree-master however the source has been renamed to buster. Changing it in two locations essentially fixes the issue (At the end of the download line, and at the end of the 7z line). That is not a proper fix but it is *a* fix.
Source:
https://github.com/RPi-Distro/firmware-nonfree/tree/buster/brcm

**Comment by bartsmit** [comment]
Hi @Rojikku,

Can you give more details on your fix perhaps? I manage to change the download line in build-image.sh but I can't work out the correct syntax for the 7z command.

Even better; could you run a diff between your file and the @sgielen version and post the patch file here please?

Thanks,

Bart...

**Comment by Rojikku** [comment]
Hey @bartsmit 
Not going to lie I deleted it in the end because of other issue with RPi I was having.

https://github.com/sgielen/picl-k3os-image-generator/blob/master/build-image.sh
Line 161, change master.zip to buster.zip
Line 318, change nonfree-master/brcm to nonfree-buster/brcm

Issue being the repo was renamed, so you have to download it at the new name. What it's saved as is irrelevant, but if you don't change the folder it's trying to extract to the new name, it won't exist.

**Comment by bartsmit** [comment]
Thanks @Rojikku, your guidance worked a treat. New build script added for posterity

Bart...
[build-image.sh.txt](https://github.com/sgielen/picl-k3os-image-generator/files/7598942/build-image.sh.txt)

**Comment by sgielen** [comment]
Merged #47, that should fix this? Please reopen if it doesn't!
