### ISSUE TITLE
2 calls to udevadm which cannot be found.

### ISSUE THREAD

**Issue by Roflincopter** [sgielen/picl-k3os-image-generator#7]
During first boot around the time the filesystem gets resized 2 calls are being made to udevadm which cannot be found (on a RPI-3B).

**Comment by sgielen** [comment]
Yeah, I had them too, but they are harmless... I might check if I can add a `2>&1 | grep -v udevadm` or something like that to hide them.

**Comment by sgielen** [comment]
Closing all issues, because the project is archived. Thank you for being a contributor and/or user!
